version: '3.5'

services:
  fb:
    image: docker.elastic.co/beats/filebeat:7.17.3
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/logs:ro
    environment:
      - --strict.perms=false
    networks:
      - dev

networks:
  dev:
    name: dev-bridge
    driver: bridge 