filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

# filebeat.autodiscover:
#   providers:
#     - type: docker
#       hints.enabled: true

setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"
setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 1

processors:
- add_cloud_metadata: ~

filebeat.inputs:
- type: filestream
  id: log_demo
  paths:
    - /logs/*.log

output.elasticsearch:
  hosts: 'http://es7_01:9200'