version: '3.5'

services: 
  xxl-job-mysql:
    image: mysql:8.0
    container_name: xxl-job-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
    volumes:
      - ${VOLUME_PATH}/xxl-job-mysql:/var/lib/mysql
      - ./xxl-job.sql:/docker-entrypoint-initdb.d/xxl-job.sql
    restart: always
    networks:
      - kazma_net
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  xxl-job:
    image: xuxueli/xxl-job-admin:2.2.0
    container_name: my-xxl-job
    restart: always
    ports: 
      - 9010:8080
    volumes: 
      - ${VOLUME_PATH}/xxl-job/applogs:/data/applogs
    networks: 
      - kazma_net
    environment: 
      TZ: Asia/Shanghai
      PARAMS: |-
        "--spring.datasource.url=jdbc:mysql://xxl-job-mysql:3306/xxl_job \ 
        --spring.datasource.username=root \ 
        --spring.datasource.password=pw123456 \
        --spring.mail.host=smtp.163.com \ 
        --spring.mail.username=kazma_todo@163.com \
        --spring.mail.password="
    depends_on: 
      - xxl-job-mysql


networks:
  kazma_net:
    name: kazma_network