version: '3.5'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.3
    container_name: kibana7
    ports:
      - 5601:5601
    volumes:
      - ~./kibana/config:/usr/share/kibana/config
      - ~/docker/kibana/data:/usr/share/kibana/data
    depends_on:
      - elasticsearch
    networks:
      - dev
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    container_name: es7_01
    environment:
      - discovery.type=single-node
    volumes:
      - ./elasticsearch/config:/usr/share/elasticsearch/config
      - ~/docker/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - dev

networks:
  dev:
    name: dev-bridge
    driver: bridge
