version: '3.8'

services:
  prometheus-server:
    image: prom/prometheus:latest
    container_name: my_prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    networks:
      - dev
    volumes:
      - ./config:/etc/prometheus

networks:
  dev:
    name: dev-bridge
    driver: bridge 
