version: '3.5'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb-dev
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pw123456
    volumes:
      - ~/docker/mongo/data/db:/data/db
    networks:
      - dev

networks:
  dev:
    name: dev-bridge
    driver: bridge
