version: '3.5'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb-dev
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pw123456
    volumes:
      - ~/docker/mongo/data/db:/data/db
    networks:
      - dev
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 27018:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pw123456
      ME_CONFIG_MONGODB_URL: mongodb://admin:pw123456@mongodb-dev:27017/
    networks:
      - dev

networks:
  dev:
    name: dev-bridge
    driver: bridge
