version: '3.5'

services:
  mongo:
    image: mongo
    container_name: mongodb-dev
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${PASS}
    volumes:
      - ${VOLUME_PATH}/data/db:/data/db
