version: '3.5'

services:
  consul:
    image: consul:latest
    container_name: consul-dev
    restart: always
    ports:
      - 8500:8500
    volumes:
      - ~/docker/consul:/consul/data
    environment:
      CONSUL_BIND_INTERFACE: eth0
    networks:
      - dev

networks:
  dev:
    name: dev-bridge
    driver: bridge
