version: '3.1'

services:
  v2ray:
    image: v2ray/official
    restart: always
    ports:
      - 23333:23333
    volumes:
      - ~/v2ray/config:/etc/v2ray
      - ~/v2ray/logs:/var/log/v2ray
    command: v2ray --config=/etc/v2ray/config.json
    
