version: '3.5'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack-dev
    ports:
      - 6379:6379
      - 8380:8001
    volumes:
      - ~/docker/redis-stack/data:/data
      - ~/docker/redis-stack/redis-stack.conf:/redis-stack.conf
    restart: always
    networks:
      - dev

networks:
  dev:
    name: dev-bridge
    driver: bridge
