version: '3'

services:
  server:
    image: zadam/trilium
    container_name: trilium-server
    volumes:
      - ~/trilium-data:/home/node/trilium-data
    ports:
      - "9002:8080"
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: unless-stopped
