version: '3.5'

services:
  hbbs:
    image: rustdesk/rustdesk-server
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    volumes:
      - ~/hbbs:/root
    network_mode: host
    command: hbbs -r ${relay_server}
  hbbr:
    image: rustdesk/rustdesk-server
    container_name: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    volumes:
      - ~/hbbr:/root
    network_mode: host
    command: hbbr
