version: '3.5'

services:
  mongo:
    image: mongo
    container_name: my-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${PASS}
    networks:
      - kazma_net

networks:
  kazma_net:
    name: kazma_network