receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  # otlp:
  #   endpoint: otelcol:4317
  # Data sources: traces, metrics, logs
  logging:
    loglevel: debug
  # Data sources: metrics
  prometheus:
    endpoint: "prometheus:9090"
    namespace: "default"
  # Data sources: traces
  jaeger:
    endpoint: "jaeger-all-in-one:14250"
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check,pprof,zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]