version: '3.5'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pw123456
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - dev
    ports:
      - 5432:5432
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 5431:8080
    depends_on:
      - postgres
    networks:
      - dev

networks:
  dev:
    name: dev-bridge
    driver: bridge

volumes:
  postgres-db:
    driver: local
    name: postgres-db