version: '3.5'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pw123456
    volumes:
      - ~/docekr/postgresql/data:/var/lib/postgresql/data
    networks:
      - dev
    ports:
      - 5432:5432
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 5431:8080
    depends_on:
      - postgres-dev
    networks:
      - dev

networks:
  dev:
    name: dev-bridge
    driver: bridge
