apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  podMonitorSelector:
    matchLabels:
      team: frontend
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: true
---
kind: Service
apiVersion: v1
metadata:
  name: prometheus-svc-i
spec:
  selector:
    prometheus: prometheus
  ports:
    - name: web
      port: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc-np
spec:
  type: NodePort
  ports:
    - name: web
      nodePort: 30900
      port: 9090
      protocol: TCP
      targetPort: web
  selector:
    prometheus: prometheus
