version: '3.5'

services:
  mongo01:
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    image: mongo
    container_name: mongo-p
    restart: always
    ports:
      - 27017:27017
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: admin
    #  MONGO_INITDB_ROOT_PASSWORD: ${PASS}
    # volumes:
      #- ${VOLUME_PATH}/mongodb-p/db:/data/db
      #- ${VOLUME_PATH}/mongodb-p/config:/etc/config
    networks:
      - kazma_net
    command: mongod --replSet kazma-rs
  mongos1:
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    image: mongo
    container_name: mongo-s1
    restart: always
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: admin
    #  MONGO_INITDB_ROOT_PASSWORD: ${PASS}
    #volumes:
      #- ${VOLUME_PATH}/mongodb-s1/db:/data/db
      #- ${VOLUME_PATH}/mongodb-s1/config:/etc/config
    networks:
      - kazma_net
    command: mongod --replSet kazma-rs
  mongos2:
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    image: mongo
    container_name: mongo-s2
    restart: always
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: admin
    #  MONGO_INITDB_ROOT_PASSWORD: ${PASS}
    #volumes:
      #- ${VOLUME_PATH}/mongodb-s2/db:/data/db
      #- ${VOLUME_PATH}/mongodb-s2/config:/etc/config
    networks:
      - kazma_net
    command: mongod --replSet kazma-rs

networks:
  kazma_net:
    name: kazma_network