version: '3.5'

services: 
  xxl-job-mysql:
    image: mysql:8.0
    container_name: xxl-job-mysql
    environment:
      MYSQL_ROOT_PASSWORD: pw123456
    volumes:
      - ~/docker/xxl-job-mysql:/var/lib/mysql
      - xxl-job.sql:/docker-entrypoint-initdb.d/xxl-job.sql
    restart: always
    networks:
      - xxl_bridge
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  xxl-job:
    image: xuxueli/xxl-job-admin:2.2.0
    container_name: my-xxl-job
    restart: always
    ports: 
      - 9010:8080
    volumes: 
      - ~/docker/xxl-job/applogs:/data/applogs
    networks: 
      - xxl_bridge
    environment: 
      TZ: Asia/Shanghai
      PARAMS: "--spring.datasource.url=jdbc:mysql://xxl-job-mysql:3306/xxl_job \ 
        --spring.datasource.username=root \ 
        --spring.datasource.password=pw123456 \
        --spring.mail.host=smtp.163.com \ 
        --spring.mail.username=kazmazeng@163.com \
        --spring.mail.password="
    depends_on: 
      - xxl-job-mysql

networks:
  xxl_bridge:
    name: xxl_bridge