version: "3.8"

services:
  jenkins-server:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins-server
    restart: unless-stopped
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - 7000:8080
      - 50000:50000
    volumes:
      - ~/docker/jenkins_home:/var/jenkins_home
    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge
