version: '3.5'

services:
  jenkins-server:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    environment: 
      TZ: 'Asia/Shanghai'
    ports:
      - 7000:8080
      - 50000:50000
    volumes:
      - ~/docker_data/jenkins_home:/var/jenkins_home
    restart: always

