version: '3.5'

services: 
  rabbotmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-dev
    restart: always
    ports: 
      - 5672:5672
      - 15672:15672
    hostname: rabbitmq-dev
    environment: 
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: pw123456
    networks:
      - dev

networks:
  dev:
    name: dev-bridge
    driver: bridge
