apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  # key: is filename, value: file content
  grafana.ini: |
    instance_name = ${HOSTNAME}

    [server]
    root_url = http://localhost:3000/grafana
    serve_from_sub_path = true
