version: '3.5'

services:
  valkey:
    image: valkey/valkey:7.2-alpine
    container_name: valkey-dev
    ports:
      - 6380:6379
    volumes:
      - ~/docker/valkey/data/data:/data
      #- ~/docker/valkey/config/valkey.conf:/usr/local/etc/valkey/valkey.conf
    restart: always
    networks:
      - dev

networks:
  dev:
    name: dev-bridge
    driver: bridge
