version: "3.8"

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    networks:
      - dev

networks:
  dev:
    name: dev-bridge
    driver: bridge
