version: '3.5'

services:
  postgres:
    image: postgres
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${PASS}
    volumes:
      - ${VOLUME_PATH}/postgres:/var/lib/postgresql/data
    networks:
      - kazma_net
    ports:
      - 5432:5432
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 5431:8080
    networks:
      - kazma_net

networks:
  kazma_net:
    name: kazma_network