server.host: "0.0.0.0"
i18n.locale: zh-CN
server.shutdownTimeout: "5s"
elasticsearch.hosts: [ "http://es7_01:9200" ]
elasticsearch.username: elastic
elasticsearch.password: pw123456
monitoring.ui.container.elasticsearch.enabled: true