version: '3.9'
services:
  kavita:
    image: kizaing/kavita:latest # Change latest to nightly for latest develop builds (can't go back to stable)
    container_name: kavita
    volumes:
      - ~/docker/kavita/manga:/manga # Manga is just an example you can have the name you want. See the following
      - ~/docker/kavita/comics:/comics # Use as many as you want
      - ~/docker/kavita/books:/books #
      - ~/docker/kavita/config:/kavita/config
        # Change './data if you want to have the config files in a different place.
        # /kavita/config must not be changed
    environment:
      - TZ=Your/Timezone
    ports:
      - "5000:5000" # Change the public port (the first 5000) if you have conflicts with other services
    restart: unless-stopped
