version: '3.5'

services:
  postgres:
    image: postgres
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${PASS}
    volumes:
      - ${VOLUME_PATH}/postgres:/var/lib/postgresql/data
    networks:
      - dev_network
    ports:
      - 5432:5432
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 5431:8080
    networks:
      - dev_network

networks:
  dev_network:
    name: dev_network