services:
    open-webui:
        image: ghcr.io/open-webui/open-webui:main
        container_name: open-webui
        ports:
            - "3000:8080"
        environment:
            - OLLAMA_BASE_URL=http://192.168.50.222:11434
        # volumes:
        #     - open-webui:/app/backend/data
        restart: always

volumes:
    open-webui: