version: '3.5'

services:
  redis:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: my-redis
    ports:
      - 6379:6379
    #volumes:
    #  - ${VOLUME_PATH}/redis:/redis_data
    restart: always
    # logging:
    #   driver: syslog
    networks:
      - kazma_net

networks:
  kazma_net:
    name: kazma_network