version: '3.5'

services:
  v2ray:
    image: v2ray/official
    restart: always
    ports:
      - 80:23333
    volumes:
      - ./config.json:/etc/v2ray/config.json
    command: v2ray --config=/etc/v2ray/config.json
    
